### ISSUE TITLE
signAndExecuteTransaction Error

### ISSUE THREAD

**Issue by wowok-ai** [suiet/wallet-kit#316]
```
const ret:any = await wallet.signAndExecuteTransaction({transaction:props.txb});
```

```
Error: Rejected from user
    at dapp-interface.js:1:60615
    at dapp-interface.js:1:16150
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
    at dapp-interface.js:1:60532
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
    at dapp-interface.js:1:16143
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
```

During the use of wallet-kit, the wallet UI will flash twice, and the signature transaction will eventually succeed, but an exception will still be thrown.

**Comment by bruceeewong** [comment]
Roger that. Will look into this soon.

**Comment by bruceeewong** [comment]
@wowok-ai Hi, would you mind providing a minimum reproducible codebase for me to detect the issue?

**Comment by wowok-ai** [comment]
ok

**Comment by bruceeewong** [comment]
Closed due to no reaction for a long time
